colormap: 1
date_format: '%d-%m-%Y'
err_default_tag: Error
err_pattern: '{crimson}[{time}] {red}{tag}{snow} : {firebrick}{message}'
file_log: true
log_default_tag: Log
log_pattern: '{greenyellow}[{time}] {lightgreen}{tag}{snow} : {mediumspringgreen}{message}'
logname: log_{time}
logtime: '%d-%m-%Y_%H-%M'
rea_default_tag: Read
rea_pattern: '{cyan}[{time}] {lightcyan}{tag}{snow} : {paleturquoise}{message} > {mediumslateblue}[{readed}]'
tag_length: 10
time_format: '%H:%M:%S'
tip_default_tag: Tip
tip_pattern: '{fuchsia}[{time}] {magenta}{tag}{snow} : {mediumorchid}{message}'
wrn_default_tag: Warn
wrn_pattern: '{darkorange}[{time}] {orange}{tag}{snow} : {gold}{message}'

